from pathlib import Path

LOGO_PATH = Path(__file__).parent.joinpath("images").joinpath("logo.jpg").absolute()
LOGO_ICO_PATH = Path(__file__).parent.joinpath("images").joinpath("logo.ico").absolute()

DICTIONARY_MAPPING = {
    "business_code": "Mã số doanh nghiệp",
    "charter_capital": "Vốn điều lệ",
    "company_abbr": "Tên viết tắt",
    "company_name_vn": "Tên công ty (Tiếng Việt)",
    "company_name_en": "Tên công ty (Tiếng Anh)",
    "email": "Email",
    "initial_registration_date": "Ngày đăng ký lần đầu",
    "number_of_changes": "Lần thay đổi",
    "par_value": "Mệnh giá cổ phần",
    "phone": "Số điện thoại",
    "total_shares": "Tổng số cổ phần",
    "main_business_activity": "Hoạt động kinh doanh chính",
    "office_address": "Địa chỉ văn phòng",
    "organizational_management_structure": "Cơ cấu tổ chức quản lý",
    "birth_date": "Ngày sinh",
    "ethnicity": "Dân tộc",
    "full_name": "Họ và tên",
    "gender": "Giới tính",
    "id_type": "Loại giấy tờ",
    "id_number": "Số CMND/CCCD",
    "issue_date": "Ngày cấp",
    "nationality": "Quốc tịch",
    "position": "Chức vụ",
    "financial_statement": "Báo cáo tình hình tài chính",
    "income_statement": "Báo cáo kết quả kinh doanh",
    # Thu nhập từ tài sản tài chính
    "interest_and_fee_income_from_financial_assets_recognized_through_p_and_l": "Thu nhập lãi và phí từ tài sản tài chính ghi nhận thông qua lãi/lỗ",
    "interest_income_from_financial_assets_recognized_through_p_and_l": "Thu nhập lãi từ tài sản tài chính ghi nhận thông qua lãi/lỗ",
    "increase_decrease_in_fair_value_of_financial_assets_recognized_through_p_and_l": "Lãi/(lỗ) từ thay đổi giá trị hợp lý của tài sản tài chính",
    "dividend_and_interest_income_from_financial_assets_recognized_through_p_and_l": "Thu nhập cổ tức và lãi từ tài sản tài chính",
    "decrease_in_fair_value_of_outstanding_warrants": "Lãi từ giảm giá trị hợp lý của chứng quyền đang lưu hành",
    "interest_income_from_held_to_maturity_investments": "Thu nhập lãi từ các khoản đầu tư nắm giữ đến ngày đáo hạn",
    "interest_income_from_loans_and_receivables": "Thu nhập lãi từ các khoản cho vay và phải thu",
    "interest_income_from_available_for_sale_financial_assets": "Thu nhập lãi từ tài sản tài chính sẵn sàng để bán",
    # Doanh thu hoạt động
    "brokerage_revenue": "Doanh thu môi giới chứng khoán",
    "underwriting_revenue": "Doanh thu bảo lãnh phát hành chứng khoán",
    "investment_advisory_revenue": "Doanh thu tư vấn đầu tư chứng khoán",
    "securities_custody_revenue": "Doanh thu lưu ký chứng khoán",
    "financial_advisory_revenue": "Doanh thu tư vấn tài chính",
    "other_operating_income": "Thu nhập hoạt động khác",
    "total_operating_revenue": "Tổng doanh thu hoạt động",
    # Chi phí hoạt động
    "interest_expense_on_financial_assets_recognized_through_p_and_l": "Chi phí lãi và phí cho tài sản tài chính ghi nhận thông qua lãi/lỗ",
    "interest_expense": "Chi phí lãi",
    "decrease_in_fair_value_of_financial_assets": "Lỗ từ giảm giá trị hợp lý của tài sản tài chính",
    "transaction_fees_for_financial_assets": "Phí giao dịch tài sản tài chính",
    "increase_in_fair_value_of_outstanding_warrants": "Lỗ từ tăng giá trị hợp lý của chứng quyền đang lưu hành",
    "provisions_for_impairment_of_financial_assets": "Chi phí dự phòng suy giảm giá trị tài sản tài chính",
    "operating_expense": "Chi phí hoạt động",
    "brokerage_fees": "Chi phí môi giới chứng khoán",
    "underwriting_and_bond_issuance_costs": "Chi phí bảo lãnh phát hành và chi phí phát hành trái phiếu",
    "investment_advisory_expenses": "Chi phí tư vấn đầu tư chứng khoán",
    "securities_custody_expenses": "Chi phí lưu ký chứng khoán",
    "financial_advisory_expenses": "Chi phí tư vấn tài chính",
    "other_operating_expenses": "Chi phí hoạt động khác",
    "total_operating_expenses": "Tổng chi phí hoạt động",
    # Thu nhập và chi phí tài chính
    "increase_decrease_in_fair_value_of_exchange_rate_and_unrealized": "Lãi/(lỗ) chênh lệch tỷ giá hối đoái đã thực hiện",
    "interest_income_from_deposits": "Thu nhập lãi tiền gửi",
    "other_investment_income": "Thu nhập đầu tư khác",
    "total_financial_operating_revenue": "Tổng thu nhập tài chính",
    "increase_decrease_in_fair_value_of_exchange_rate_loss": "Lỗ chênh lệch tỷ giá hối đoái chưa thực hiện",
    "interest_expense_on_borrowings": "Chi phí lãi vay",
    "other_financial_expenses": "Chi phí tài chính khác",
    "total_financial_expenses": "Tổng chi phí tài chính",
    # Chi phí quản lý và lợi nhuận
    "general_and_administrative_expenses": "Chi phí quản lý doanh nghiệp",
    "operating_profit": "Lợi nhuận thuần từ hoạt động kinh doanh",
    "other_income": "Thu nhập khác",
    "other_expenses": "Chi phí khác",
    "net_other_income_and_expenses": "Thu nhập/(chi phí) khác - ròng",
    "accounting_profit_before_tax": "Tổng lợi nhuận kế toán trước thuế",
    "realized_profit": "Lợi nhuận đã thực hiện",
    "unrealized_profit_loss": "Lợi nhuận/(lỗ) chưa thực hiện",
    # Thuế và lợi nhuận sau thuế
    "total_corporate_income_tax": "Chi phí thuế thu nhập doanh nghiệp",
    "current_corporate_income_tax_expense": "Chi phí thuế thu nhập doanh nghiệp hiện hành",
    "benefit_from_deferred_income_tax_expense": "Lợi ích/(chi phí) thuế thu nhập hoãn lại",
    "net_profit_after_tax": "Lợi nhuận sau thuế thu nhập doanh nghiệp",
    "profit_attributable_to_equity_holders": "Lợi nhuận sau thuế của cổ đông công ty mẹ",
    "profit_attributable_to_non_controlling_interests": "Lợi nhuận sau thuế của cổ đông không kiểm soát",
}
