DIMENSIONAL_MAPPING = {
    "roe": {
        "fields": [
            {
                "display_name": "ROE",
                "field_path": "calculated_metrics.roe",
                "data_type": "Ratio",
                "show_difference": True,
            },
            {
                "display_name": "ROS",
                "field_path": "calculated_metrics.ros",
                "data_type": "Ratio",
                "show_difference": True,
            },
            {
                "display_name": "AU",
                "field_path": "calculated_metrics.au",
                "data_type": "Ratio",
                "show_difference": True,
            },
            {
                "display_name": "EM",
                "field_path": "calculated_metrics.em",
                "data_type": "Ratio",
                "show_difference": True,
            },
        ]
    },
    "ros": {
        "fields": [
            {
                "display_name": "ROS",
                "field_path": "calculated_metrics.ros",
                "data_type": "Ratio",
                "show_difference": True,
            },
            {
                "display_name": "Lợi nhuận sau thuế",
                "field_path": "income_statement.net_profit_after_tax",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Doanh thu hoạt động",
                "field_path": "income_statement.total_operating_revenue",
                "data_type": "VND",
                "show_difference": True,
            },
        ]
    },
    "au": {
        "fields": [
            {
                "display_name": "AU",
                "field_path": "calculated_metrics.au",
                "data_type": "Ratio",
                "show_difference": True,
            },
            {
                "display_name": "Doanh thu hoạt động",
                "field_path": "income_statement.total_operating_revenue",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tổng tài sản bình quân",
                "field_path": "calculated_metrics.avg_total_assets",
                "data_type": "VND",
                "show_difference": True,
            },
        ]
    },
    "em": {
        "fields": [
            {
                "display_name": "EM",
                "field_path": "calculated_metrics.em",
                "data_type": "Ratio",
                "show_difference": True,
            },
            {
                "display_name": "Tổng tài sản bình quân",
                "field_path": "calculated_metrics.avg_total_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Vốn chủ sở hữu",
                "field_path": "financial_statement.owners_equity",
                "data_type": "VND",
                "show_difference": True,
            },
        ]
    },
    "operating_revenue": {
        "fields": [
            {
                "display_name": "Doanh thu hoạt động",
                "field_path": "income_statement.total_operating_revenue",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lãi từ các tài sản tài chính ghi nhận thông qua lãi/lỗ",
                "field_path": "income_statement.interest_income_from_financial_assets_recognized_through_p_and_l",
                "show_difference": True,
            },
            {
                "display_name": "Lãi từ các tài sản tài chính ghi nhận thông qua lãi/lỗ",
                "field_path": "income_statement.interest_income_from_financial_assets_recognized_through_p_and_l",
                "show_difference": True,
            },
            {
                "display_name": "Chênh lệch tăng về đánh giá lại các tài sản tài chính ghi nhận thông qua lãi/lỗ",
                "field_path": "income_statement.increase_decrease_in_fair_value_of_financial_assets_recognized_through_p_and_l",
                "show_difference": True,
            },
            {
                "display_name": "Cổ tức, tiền lãi phát sinh từ tài sản tài chính ghi nhận thông qua lãi/lỗ",
                "field_path": "income_statement.dividend_and_interest_income_from_financial_assets_recognized_through_p_and_l",
                "show_difference": True,
            },
            {
                "display_name": "Lãi từ các khoản đầu tư nắm giữ đến ngày đáo hạn",
                "field_path": "income_statement.interest_income_from_held_to_maturity_investments",
                "show_difference": True,
            },
            {
                "display_name": "Lãi từ các khoản cho vay và phải thu",
                "field_path": "income_statement.interest_income_from_loans_and_receivables",
                "show_difference": True,
            },
            {
                "display_name": "Lãi từ tài sản tài chính sẵn sàng để bán",
                "field_path": "income_statement.interest_income_from_available_for_sale_financial_assets",
                "show_difference": True,
            },
            {
                "display_name": "Lãi từ các công cụ phái sinh phòng ngừa rủi ro",
                "field_path": "income_statement.gain_from_hedging_derivatives",
                "show_difference": True,
            },
            {
                "display_name": "Doanh thu nghiệp vụ môi giới chứng khoán",
                "field_path": "income_statement.brokerage_revenue",
                "show_difference": True,
            },
            {
                "display_name": "Doanh thu nghiệp vụ bảo lãnh, đại lý phát hành chứng khoán",
                "field_path": "income_statement.underwriting_revenue",
                "show_difference": True,
            },
            {
                "display_name": "Doanh thu nghiệp vụ tư vấn đầu tư chứng khoán",
                "field_path": "income_statement.investment_advisory_revenue",
                "show_difference": True,
            },
            {
                "display_name": "Doanh thu nghiệp vụ lưu ký chứng khoán",
                "field_path": "income_statement.securities_custody_revenue",
                "show_difference": True,
            },
            {
                "display_name": "Doanh thu hoạt động tư vấn tài chính",
                "field_path": "income_statement.financial_advisory_revenue",
                "show_difference": True,
            },
            {
                "display_name": "Thu nhập hoạt động khác",
                "field_path": "income_statement.other_operating_income",
                "show_difference": True,
            },
        ]
    },
    "profit": {
        "fields": [
            {
                "display_name": "Lợi nhuận sau thuế",
                "field_path": "income_statement.net_profit_after_tax",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Doanh thu hoạt động",
                "field_path": "income_statement.total_operating_revenue",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí hoạt động",
                "field_path": "income_statement.operating_expense",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lỗ các tài sản tài chính ghi nhận thông qua lãi/lỗ",
                "field_path": "income_statement.interest_expense_on_financial_assets_recognized_through_p_and_l",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lỗ bán các tài sản tài chính",
                "field_path": "income_statement.interest_expense",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chênh lệch giảm đánh giá lại các tài sản tài chính",
                "field_path": "income_statement.decrease_in_fair_value_of_financial_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí giao dịch mua các tài sản tài chính",
                "field_path": "income_statement.transaction_fees_for_financial_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lỗ các khoản đầu tư nắm giữ đến ngày đáo hạn",
                "field_path": "income_statement.loss_from_held_to_maturity_investments",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lỗ và ghi nhận chênh lệch đánh giá theo giá trị hợp lý tài sản tài chính sẵn sàng để bán",
                "field_path": "income_statement.loss_and_recognition_of_fair_value_difference_of_available_for_sale_financial_assets_upon_reclassification",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí dự phòng tài sản tài chính, xử lý tổn thất các khoản phải thu khó đòi và lỗ suy giảm tài sản tài chính và chi phí đi vay của các khoản cho vay",
                "field_path": "income_statement.provisions_for_impairment_of_financial_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lỗ từ các tài sản tài chính phái sinh phòng ngừa rủi ro",
                "field_path": "income_statement.loss_from_hedging_derivatives",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí hoạt động tự doanh",
                "field_path": "income_statement.operating_expense",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí nghiệp vụ môi giới chứng khoán",
                "field_path": "income_statement.brokerage_fees",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí nghiệp vụ lưu ký chứng khoán",
                "field_path": "income_statement.securities_custody_expenses",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí hoạt động tư vấn tài chính",
                "field_path": "income_statement.financial_advisory_expenses",
                "data_type": "VND",
                "show_difference": True,
            },
        ]
    },
    "assets": {
        "fields": [
            {
                "display_name": "Tổng cộng tài sản",
                "field_path": "financial_statement.total_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản ngắn hạn",
                "field_path": "financial_statement.short_term_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản tài chính",
                "field_path": "financial_statement.financial_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tiền và các khoản tương đương tiền",
                "field_path": "financial_statement.cash_and_cash_equivalents",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tiền",
                "field_path": "financial_statement.cash",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các khoản tương đương tiền",
                "field_path": "financial_statement.cash_equivalents",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các tài sản tài chính ghi nhận thông qua lãi/lỗ (FVTPL)",
                "field_path": "financial_statement.financial_assets_at_fair_value_through_profit_or_loss",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các khoản đầu tư nắm giữ đến ngày đáo hạn (HTM)",
                "field_path": "financial_statement.held_to_maturity_investments",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các khoản cho vay",
                "field_path": "financial_statement.loans",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản tài chính sẵn sàng để bán (AFS)",
                "field_path": "financial_statement.available_for_sale_financial_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Dự phòng suy giảm giá trị các tài sản tài chính và tài sản thế chấp",
                "field_path": "financial_statement.provision_for_impairment_of_financial_assets_and_collateral",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các khoản phải thu",
                "field_path": "financial_statement.receivables",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Phải thu bán các tài sản tài chính",
                "field_path": "financial_statement.receivables_from_sale_of_financial_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Phải thu và dự thu cổ tức, tiền lãi các tài sản tài chính",
                "field_path": "financial_statement.dividends_and_interest_receivable",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Phải thu cổ tức, tiền lãi đến ngày nhận",
                "field_path": "financial_statement.dividends_and_interest_receivable_due",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Dự thu cổ tức, tiền lãi chưa đến ngày nhận",
                "field_path": "financial_statement.accrued_dividends_and_interest_receivable",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Trả trước cho người bán",
                "field_path": "financial_statement.prepayments_to_suppliers",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Phải thu các dịch vụ công ty chứng khoán cung cấp",
                "field_path": "financial_statement.receivables_from_securities_services",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Phải thu nội bộ",
                "field_path": "financial_statement.internal_receivables",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Phải thu về lỗi giao dịch chứng khoán",
                "field_path": "financial_statement.receivables_from_securities_trading_errors",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các khoản phải thu khác",
                "field_path": "financial_statement.other_receivables",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Dự phòng suy giảm giá trị các khoản phải thu",
                "field_path": "financial_statement.provision_for_doubtful_debts",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản ngắn hạn khác",
                "field_path": "financial_statement.other_short_term_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tạm ứng",
                "field_path": "financial_statement.advances",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Vật tư văn phòng, công cụ, dụng cụ",
                "field_path": "financial_statement.office_supplies_and_tools",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí trả trước ngắn hạn",
                "field_path": "financial_statement.short_term_prepaid_expenses",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Cầm cố, thế chấp, ký quỹ, ký cược ngắn hạn",
                "field_path": "financial_statement.short_term_collateral_and_deposits",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Thuế giá trị gia tăng được khấu trừ",
                "field_path": "financial_statement.deductible_value_added_tax",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Thuế và các khoản khác phải thu Nhà nước",
                "field_path": "financial_statement.taxes_and_other_receivables_from_the_state",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản ngắn hạn khác",
                "field_path": "financial_statement.other_current_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Giao dịch mua bán lại trái phiếu Chính phủ",
                "field_path": "financial_statement.repurchase_agreements_for_government_bonds",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Dự phòng suy giảm giá trị tài sản ngắn hạn khác",
                "field_path": "financial_statement.provision_for_impairment_of_other_short_term_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản dài hạn",
                "field_path": "financial_statement.long_term_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản tài chính dài hạn",
                "field_path": "financial_statement.long_term_financial_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các khoản phải thu dài hạn",
                "field_path": "financial_statement.long_term_receivables",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các khoản đầu tư",
                "field_path": "financial_statement.investments",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các khoản đầu tư nắm giữ đến ngày đáo hạn",
                "field_path": "financial_statement.long_term_held_to_maturity_investments",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Đầu tư vào công ty con",
                "field_path": "financial_statement.investments_in_subsidiaries",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Đầu tư vào công ty liên doanh, liên kết",
                "field_path": "financial_statement.investments_in_joint_ventures_and_associates",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Đầu tư dài hạn khác",
                "field_path": "financial_statement.other_long_term_investments",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Dự phòng suy giảm tài sản tài chính dài hạn",
                "field_path": "financial_statement.provision_for_impairment_of_long_term_financial_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản cố định",
                "field_path": "financial_statement.fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản cố định hữu hình",
                "field_path": "financial_statement.tangible_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Nguyên giá tài sản cố định hữu hình",
                "field_path": "financial_statement.tangible_fixed_assets_cost",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Giá trị hao mòn lũy kế tài sản cố định hữu hình",
                "field_path": "financial_statement.accumulated_depreciation_of_tangible_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Đánh giá tài sản cố định hữu hình theo giá trị hợp lý",
                "field_path": "financial_statement.fair_value_adjustment_of_tangible_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản cố định thuê tài chính",
                "field_path": "financial_statement.finance_lease_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Nguyên giá tài sản cố định thuê tài chính",
                "field_path": "financial_statement.finance_lease_fixed_assets_cost",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Giá trị hao mòn lũy kế tài sản cố định thuê tài chính",
                "field_path": "financial_statement.accumulated_depreciation_of_finance_lease_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Đánh giá tài sản cố định thuê tài chính theo giá trị hợp lý",
                "field_path": "financial_statement.fair_value_adjustment_of_finance_lease_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản cố định vô hình",
                "field_path": "financial_statement.intangible_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Nguyên giá tài sản cố định vô hình",
                "field_path": "financial_statement.intangible_fixed_assets_cost",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Giá trị hao mòn lũy kế tài sản cố định vô hình",
                "field_path": "financial_statement.accumulated_amortization_of_intangible_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Đánh giá tài sản cố định vô hình theo giá trị hợp lý",
                "field_path": "financial_statement.fair_value_adjustment_of_intangible_fixed_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Bất động sản đầu tư",
                "field_path": "financial_statement.investment_property",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Nguyên giá bất động sản đầu tư",
                "field_path": "financial_statement.investment_property_cost",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Giá trị hao mòn lũy kế bất động sản đầu tư",
                "field_path": "financial_statement.accumulated_depreciation_of_investment_property",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Đánh giá bất động sản đầu tư theo giá trị hợp lý",
                "field_path": "financial_statement.fair_value_adjustment_of_investment_property",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí xây dựng cơ bản dở dang",
                "field_path": "financial_statement.construction_in_progress",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản dài hạn khác",
                "field_path": "financial_statement.other_long_term_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Cầm cố, thế chấp, ký quỹ, ký cược dài hạn",
                "field_path": "financial_statement.long_term_collateral_and_deposits",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chi phí trả trước dài hạn",
                "field_path": "financial_statement.long_term_prepaid_expenses",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản thuế thu nhập hoãn lại",
                "field_path": "financial_statement.deferred_tax_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tiền nộp Quỹ Hỗ trợ thanh toán",
                "field_path": "financial_statement.deposits_to_clearing_support_fund",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tài sản dài hạn khác",
                "field_path": "financial_statement.other_non_current_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Dự phòng suy giảm giá trị tài sản dài hạn",
                "field_path": "financial_statement.provision_for_impairment_of_long_term_assets",
                "data_type": "VND",
                "show_difference": True,
            },
        ]
    },
    "owners_equity": {
        "fields": [
            {
                "display_name": "Vốn chủ sở hữu",
                "field_path": "financial_statement.owners_equity",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Vốn đầu tư của chủ sở hữu",
                "field_path": "financial_statement.capital",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Vốn góp của chủ sở hữu",
                "field_path": "financial_statement.share_capital",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Cổ phiếu phổ thông có quyền biểu quyết",
                "field_path": "financial_statement.ordinary_shares_with_voting_rights",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Cổ phiếu ưu đãi",
                "field_path": "financial_statement.preferred_shares",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Thặng dư vốn cổ phần",
                "field_path": "financial_statement.share_premium",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Quyền chọn chuyển đổi trái phiếu - Cấu phần vốn",
                "field_path": "financial_statement.convertible_bonds_equity_component",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Vốn khác của chủ sở hữu",
                "field_path": "financial_statement.other_capital",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Cổ phiếu quỹ",
                "field_path": "financial_statement.treasury_shares",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chênh lệch đánh giá tài sản theo giá trị hợp lý",
                "field_path": "financial_statement.fair_value_adjustment_of_assets",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Chênh lệch tỷ giá hối đoái",
                "field_path": "financial_statement.foreign_exchange_differences",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Quỹ dự trữ bổ sung vốn điều lệ",
                "field_path": "financial_statement.supplementary_charter_capital_reserve",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Quỹ dự phòng tài chính và rủi ro nghiệp vụ",
                "field_path": "financial_statement.financial_reserve_and_business_risk_fund",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Các Quỹ khác thuộc vốn chủ sở hữu",
                "field_path": "financial_statement.other_funds_under_owners_equity",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lợi nhuận chưa phân phối",
                "field_path": "financial_statement.retained_earnings",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lợi nhuận sau thuế đã thực hiện",
                "field_path": "financial_statement.realized_retained_earnings",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Lợi nhuận chưa thực hiện",
                "field_path": "financial_statement.unrealized_retained_earnings",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Nguồn kinh phí và quỹ khác",
                "field_path": "financial_statement.funding_and_other_funds",
                "data_type": "VND",
                "show_difference": True,
            },
            {
                "display_name": "Tổng cộng nợ và vốn chủ sở hữu",
                "field_path": "financial_statement.total_liabilities_and_owners_equity",
                "data_type": "VND",
                "show_difference": True,
            },
        ]
    },
    "revenue_profit_table": {
        "fields": [
            {
                "display_name": "Doanh thu hoạt động",
                "field_path": "income_statement.total_operating_revenue",
                "data_type": "VND",
            },
            {
                "display_name": "Chi phí hoạt động",
                "field_path": "income_statement.total_operating_expenses",
                "data_type": "VND",
            },
            {
                "display_name": "Kết quả hoạt động",
                "field_path": "income_statement.operating_profit",
                "data_type": "VND",
            },
            {
                "display_name": "Lợi nhuận trước thuế",
                "field_path": "income_statement.accounting_profit_before_tax",
                "data_type": "VND",
            },
            {
                "display_name": "Lợi nhuận sau thuế",
                "field_path": "income_statement.net_profit_after_tax",
                "data_type": "VND",
            },
        ]
    },
    "financial_overview_table": {
        "fields": [
            {
                "display_name": "Tổng tài sản",
                "field_path": "financial_statement.total_assets",
                "data_type": "VND",
            },
            {
                "display_name": "Khoản phải thu ngắn hạn",
                "field_path": "financial_statement.receivables",
                "data_type": "VND",
            },
            {
                "display_name": "Tổng nợ phải trả",
                "field_path": "financial_statement.liabilities",
                "data_type": "VND",
            },
            {
                "display_name": "Phải trả người bán",
                "field_path": "financial_statement.short_term_trade_payables",
                "data_type": "VND",
            },
            {
                "display_name": "Vay và nợ thuê tài chính",
                "field_path": "financial_statement.short_term_borrowings_and_finance_lease_liabilities",
                "data_type": "VND",
            },
            {
                "display_name": "Vốn chủ sở hữu",
                "field_path": "financial_statement.owners_equity",
                "data_type": "VND",
            },
            {
                "display_name": "Doanh thu",
                "field_path": "income_statement.total_operating_revenue",
                "data_type": "VND",
            },
            {
                "display_name": "Chi phí bán hàng",
                "field_path": "income_statement.selling_expenses",
                "data_type": "VND",
            },
            {
                "display_name": "Chi phí quản lý doanh nghiệp",
                "field_path": "income_statement.general_and_administrative_expenses",
                "data_type": "VND",
            },
            {
                "display_name": "Lợi nhuận thuần từ hoạt động kinh doanh",
                "field_path": "income_statement.operating_profit",
                "data_type": "VND",
            },
            {
                "display_name": "Thu nhập khác",
                "field_path": "income_statement.other_income",
                "data_type": "VND",
            },
            {
                "display_name": "Chi phí khác",
                "field_path": "income_statement.other_expenses",
                "data_type": "VND",
            },
            {
                "display_name": "Chi phí lãi vay",
                "field_path": "income_statement.interest_expense_on_borrowings",
                "data_type": "VND",
            },
            {
                "display_name": "EBIT",
                "field_path": "calculated_metrics.ebit",
                "data_type": "VND",
            },
            {
                "display_name": "EBITDA",
                "field_path": "calculated_metrics.ebitda",
                "data_type": "VND",
            },
            {
                "display_name": "Lợi nhuận thuần",
                "field_path": "income_statement.net_profit_after_tax",
                "data_type": "VND",
            },
        ]
    },
    "liquidity_ratios_table": {
        "fields": [
            {
                "display_name": "Khả năng TT hiện hành",
                "field_path": "calculated_metrics.current_ratio",
                "data_type": "Ratio",
            },
            {
                "display_name": "Khả năng TT nhanh",
                "field_path": "calculated_metrics.quick_ratio",
                "data_type": "Ratio",
            },
            {
                "display_name": "Khả năng TT tức thời",
                "field_path": "calculated_metrics.cash_ratio",
                "data_type": "Ratio",
            },
        ]
    },
    "operational_efficiency_table": {
        "fields": [
            {
                "display_name": "Gross Profit Margin %",
                "field_path": "calculated_metrics.gross_profit_margin",
                "data_type": "Percentage",
            },
            {
                "display_name": "EBIT %",
                "field_path": "calculated_metrics.ebit_margin",
                "data_type": "Percentage",
            },
            {
                "display_name": "ROS %",
                "field_path": "calculated_metrics.ros",
                "data_type": "Percentage",
            },
            {
                "display_name": "ROA %",
                "field_path": "calculated_metrics.roa",
                "data_type": "Percentage",
            },
            {
                "display_name": "ROE %",
                "field_path": "calculated_metrics.roe",
                "data_type": "Percentage",
            },
            {
                "display_name": "ATO %",
                "field_path": "calculated_metrics.ato",
                "data_type": "Percentage",
            },
        ]
    },
    "leverage_table": {
        "fields": [
            {
                "display_name": "Nợ phải trả trên Tổng TS",
                "field_path": "calculated_metrics.debt_ratio",
                "data_type": "Percentage",
            },
            {
                "display_name": "Nợ dài hạn trên VCSH",
                "field_path": "calculated_metrics.long_term_debt_to_equity",
                "data_type": "Percentage",
            },
            {
                "display_name": "Hệ số TSCĐ",
                "field_path": "calculated_metrics.leverage_ratio",
                "data_type": "Ratio",
            },
            {
                "display_name": "Tốc độ gia tăng TS",
                "field_path": "calculated_metrics.asset_growth_rate",
                "data_type": "Percentage",
            },
        ]
    },
    "profitability_table": {
        "fields": [
            {
                "display_name": "LN từ HĐKD trên DT thuần",
                "field_path": "calculated_metrics.operating_profit_margin",
                "data_type": "Percentage",
            },
            {
                "display_name": "LN sau thuế trên VCSHbq",
                "field_path": "calculated_metrics.roe",
                "data_type": "Percentage",
            },
            {
                "display_name": "LN sau thuế trên TSbq",
                "field_path": "calculated_metrics.roa",
                "data_type": "Percentage",
            },
            {
                "display_name": "EBIT/chi phí lãi vay",
                "field_path": "calculated_metrics.interest_coverage_ratio",
                "data_type": "Ratio",
            },
            {
                "display_name": "Tốc độ tăng trưởng LN sau thuế",
                "field_path": "calculated_metrics.net_profit_growth_rate",
                "data_type": "Percentage",
            },
        ]
    },
    "balance_sheet_horizontal": {
        "fields": [
            {
                "display_name": "A. TÀI SẢN NGẮN HẠN",
                "is_group_header": True,
                "is_section": True,
            },
            {"display_name": "I. Tài sản tài chính", "is_group_header": True},
            {
                "display_name": "1. Tiền và các khoản tương đương tiền",
                "field_path": "financial_statement.cash_and_cash_equivalents",
                "proportion_base": "financial_statement.short_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2. Các tài sản tài chính ghi nhận thông qua lãi/lỗ",
                "field_path": "financial_statement.financial_assets_at_fair_value_through_profit_or_loss",
                "proportion_base": "financial_statement.short_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "3. Các khoản đầu tư nắm giữ đến ngày đáo hạn",
                "field_path": "financial_statement.held_to_maturity_investments",
                "proportion_base": "financial_statement.short_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "4. Các khoản cho vay",
                "field_path": "financial_statement.loans",
                "proportion_base": "financial_statement.short_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "5. Tài sản tài chính sẵn sàng để bán",
                "field_path": "financial_statement.available_for_sale_financial_assets",
                "proportion_base": "financial_statement.short_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "7. Các khoản phải thu",
                "field_path": "financial_statement.receivables",
                "proportion_base": "financial_statement.short_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {"display_name": "II. Tài sản ngắn hạn khác", "is_group_header": True},
            {
                "display_name": "7. Tài sản ngắn hạn khác",
                "field_path": "financial_statement.other_short_term_assets",
                "proportion_base": "financial_statement.short_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "B. TÀI SẢN DÀI HẠN",
                "is_group_header": True,
                "is_section": True,
            },
            {"display_name": "I. Tài sản tài chính dài hạn", "is_group_header": True},
            {
                "display_name": "2. Các khoản đầu tư",
                "field_path": "financial_statement.investments",
                "proportion_base": "financial_statement.long_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {"display_name": "II. Tài sản cố định", "is_group_header": True},
            {
                "display_name": "1. Tài sản cố định hữu hình",
                "field_path": "financial_statement.tangible_fixed_assets",
                "proportion_base": "financial_statement.long_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "3. Tài sản cố định vô hình",
                "field_path": "financial_statement.intangible_fixed_assets",
                "proportion_base": "financial_statement.long_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {"display_name": "III. Bất động sản đầu tư", "is_group_header": True},
            {
                "display_name": "Bất động sản đầu tư",
                "field_path": "financial_statement.investment_property",
                "proportion_base": "financial_statement.long_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {"display_name": "V. Tài sản dài hạn khác", "is_group_header": True},
            {
                "display_name": "Tài sản dài hạn khác",
                "field_path": "financial_statement.other_long_term_assets",
                "proportion_base": "financial_statement.long_term_assets",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "C. NỢ PHẢI TRẢ",
                "is_group_header": True,
                "is_section": True,
            },
            {"display_name": "I. Nợ phải trả ngắn hạn", "is_group_header": True},
            {
                "display_name": "1. Vay và nợ thuê tài chính ngắn hạn",
                "field_path": "financial_statement.short_term_borrowings_and_finance_lease_liabilities",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "4. Trái phiếu phát hành ngắn hạn",
                "field_path": "financial_statement.short_term_bonds_issued",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "6. Phải trả hoạt động giao dịch chứng khoán",
                "field_path": "financial_statement.payables_from_securities_trading_activities",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "8. Phải trả người bán ngắn hạn",
                "field_path": "financial_statement.short_term_trade_payables",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "10. Thuế và các khoản phải nộp Nhà nước",
                "field_path": "financial_statement.taxes_and_other_payables_to_the_state",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "17. Các khoản phải trả khác ngắn hạn",
                "field_path": "financial_statement.other_short_term_payables",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {"display_name": "II. Nợ phải trả dài hạn", "is_group_header": True},
            {
                "display_name": "1. Vay và nợ thuê tài chính dài hạn",
                "field_path": "financial_statement.long_term_borrowings_and_finance_lease_liabilities",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "4. Trái phiếu phát hành dài hạn",
                "field_path": "financial_statement.long_term_bonds_issued",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "14. Thuế thu nhập hoãn lại phải trả",
                "field_path": "financial_statement.deferred_tax_liabilities",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "11. Các khoản phải trả khác dài hạn",
                "field_path": "financial_statement.other_long_term_payables",
                "proportion_base": "financial_statement.liabilities",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "VỐN CHỦ SỞ HỮU",
                "is_group_header": True,
                "is_section": True,
            },
            {"display_name": "I. Vốn chủ sở hữu", "is_group_header": True},
            {
                "display_name": "1. Vốn đầu tư của chủ sở hữu",
                "field_path": "financial_statement.capital",
                "proportion_base": "financial_statement.owners_equity",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2. Thặng dư vốn cổ phần",
                "field_path": "financial_statement.share_premium",
                "proportion_base": "financial_statement.owners_equity",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "3. Cổ phiếu quỹ",
                "field_path": "financial_statement.treasury_shares",
                "proportion_base": "financial_statement.owners_equity",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "5. Quỹ dự phòng tài chính và rủi ro nghiệp vụ",
                "field_path": "financial_statement.financial_reserve_and_business_risk_fund",
                "proportion_base": "financial_statement.owners_equity",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "7. Lợi nhuận chưa phân phối",
                "field_path": "financial_statement.retained_earnings",
                "proportion_base": "financial_statement.owners_equity",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "TỔNG CỘNG VỐN CHỦ SỞ HỮU",
                "field_path": "financial_statement.owners_equity",
                "is_bold": True,
                "is_total_row": True,
                "show_difference": True,
            },
            {
                "display_name": "TỔNG CỘNG NỢ PHẢI TRẢ VÀ VỐN CHỦ SỞ HỮU",
                "field_path": "financial_statement.total_assets",
                "is_bold": True,
                "is_total_row": True,
                "show_difference": True,
            },
        ]
    },
    "income_statement_horizontal": {
        "fields": [
            {
                "display_name": "I. DOANH THU HOẠT ĐỘNG",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "1.1. Lãi từ các tài sản tài chính ghi nhận thông qua lãi/lỗ (FVTPL)",
                "field_path": "income_statement.interest_income_from_financial_assets_recognized_through_p_and_l",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.2. Lãi từ các khoản đầu tư nắm giữ đến ngày đáo hạn (HTM)",
                "field_path": "income_statement.interest_income_from_held_to_maturity_investments",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.3. Lãi từ các khoản cho vay và phải thu",
                "field_path": "income_statement.interest_income_from_loans_and_receivables",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.4. Lãi từ tài sản tài chính sẵn sàng để bán (AFS)",
                "field_path": "income_statement.interest_income_from_available_for_sale_financial_assets",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.6. Doanh thu nghiệp vụ môi giới chứng khoán",
                "field_path": "income_statement.brokerage_revenue",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.7. Doanh thu nghiệp vụ bảo lãnh, đại lý phát hành chứng khoán",
                "field_path": "income_statement.underwriting_revenue",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.8. Doanh thu nghiệp vụ tư vấn đầu tư chứng khoán",
                "field_path": "income_statement.investment_advisory_revenue",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.9. Doanh thu nghiệp vụ lưu ký chứng khoán",
                "field_path": "income_statement.securities_custody_revenue",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.10. Doanh thu hoạt động tư vấn tài chính",
                "field_path": "income_statement.financial_advisory_revenue",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "1.11. Thu nhập hoạt động khác",
                "field_path": "income_statement.other_operating_income",
                "proportion_base": "income_statement.total_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "II. CHI PHÍ HOẠT ĐỘNG",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "2.1. Lỗ các tài sản tài chính ghi nhận thông qua lãi/lỗ (FVTPL)",
                "field_path": "income_statement.interest_expense_on_financial_assets_recognized_through_p_and_l",
                "proportion_base": "income_statement.total_operating_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2.4. Chi phí dự phòng tài sản tài chính",
                "field_path": "income_statement.provisions_for_impairment_of_financial_assets",
                "proportion_base": "income_statement.total_operating_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2.7. Chi phí nghiệp vụ môi giới chứng khoán",
                "field_path": "income_statement.brokerage_fees",
                "proportion_base": "income_statement.total_operating_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2.8. Chi phí nghiệp vụ bảo lãnh",
                "field_path": "income_statement.underwriting_and_bond_issuance_costs",
                "proportion_base": "income_statement.total_operating_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2.9. Chi phí nghiệp vụ tư vấn đầu tư chứng khoán",
                "field_path": "income_statement.investment_advisory_expenses",
                "proportion_base": "income_statement.total_operating_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2.10. Chi phí nghiệp vụ lưu ký chứng khoán",
                "field_path": "income_statement.securities_custody_expenses",
                "proportion_base": "income_statement.total_operating_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2.11. Chi phí hoạt động tư vấn tài chính",
                "field_path": "income_statement.financial_advisory_expenses",
                "proportion_base": "income_statement.total_operating_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "2.12. Chi phí các dịch vụ khác",
                "field_path": "income_statement.other_operating_expenses",
                "proportion_base": "income_statement.total_operating_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "III. DOANH THU HOẠT ĐỘNG TÀI CHÍNH",
                "is_group_header": True,
            },
            {
                "display_name": "3.2. Lãi tiền gửi ngân hàng",
                "field_path": "income_statement.interest_income_from_deposits",
                "proportion_base": "income_statement.total_financial_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "3.1. Chênh lệch lãi tỷ giá",
                "field_path": "income_statement.increase_decrease_in_fair_value_of_exchange_rate_and_unrealized",
                "proportion_base": "income_statement.total_financial_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "3.3. Lãi bán, thanh lý đầu tư",
                "field_path": "income_statement.gain_on_disposal_of_investments_in_subsidiaries_associates_and_joint_ventures",
                "proportion_base": "income_statement.total_financial_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "3.4. Doanh thu khác về đầu tư",
                "field_path": "income_statement.other_investment_income",
                "proportion_base": "income_statement.total_financial_operating_revenue",
                "show_proportion": True,
                "show_difference": True,
            },
            {"display_name": "IV. CHI PHÍ TÀI CHÍNH", "is_group_header": True},
            {
                "display_name": "4.2. Chi phí lãi vay",
                "field_path": "income_statement.interest_expense_on_borrowings",
                "proportion_base": "income_statement.total_financial_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "4.1. Chênh lệch lỗ tỷ giá",
                "field_path": "income_statement.increase_decrease_in_fair_value_of_exchange_rate_loss",
                "proportion_base": "income_statement.total_financial_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "4.3. Lỗ bán, thanh lý đầu tư",
                "field_path": "income_statement.loss_on_disposal_of_investments_in_subsidiaries_associates_and_joint_ventures",
                "proportion_base": "income_statement.total_financial_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "4.4. Chi phí dự phòng đầu tư dài hạn",
                "field_path": "income_statement.provision_for_impairment_of_long_term_financial_investments",
                "proportion_base": "income_statement.total_financial_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "4.5. Chi phí tài chính khác",
                "field_path": "income_statement.other_financial_expenses",
                "proportion_base": "income_statement.total_financial_expenses",
                "show_proportion": True,
                "show_difference": True,
            },
            {
                "display_name": "V. CHI PHÍ BÁN HÀNG",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "Chi phí bán hàng",
                "field_path": "income_statement.selling_expenses",
                "show_difference": True,
            },
            {
                "display_name": "VI. CHI PHÍ QUẢN LÝ CÔNG TY CHỨNG KHOÁN",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "Chi phí quản lý doanh nghiệp",
                "field_path": "income_statement.general_and_administrative_expenses",
                "show_difference": True,
            },
            {
                "display_name": "VII. KẾT QUẢ HOẠT ĐỘNG",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "Lợi nhuận thuần từ hoạt động kinh doanh",
                "field_path": "income_statement.operating_profit",
                "is_bold": True,
                "show_difference": True,
            },
            {
                "display_name": "VIII. THU NHẬP KHÁC VÀ CHI PHÍ KHÁC",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "8.1. Thu nhập khác",
                "field_path": "income_statement.other_income",
                "show_difference": True,
            },
            {
                "display_name": "8.2. Chi phí khác",
                "field_path": "income_statement.other_expenses",
                "show_difference": True,
            },
            {
                "display_name": "IX. TỔNG LỢI NHUẬN KẾ TOÁN TRƯỚC THUẾ",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "Tổng lợi nhuận kế toán trước thuế",
                "field_path": "income_statement.accounting_profit_before_tax",
                "is_bold": True,
                "show_difference": True,
            },
            {
                "display_name": "9.1. Lợi nhuận đã thực hiện",
                "field_path": "income_statement.realized_profit",
                "show_difference": True,
            },
            {
                "display_name": "9.2. Lợi nhuận chưa thực hiện",
                "field_path": "income_statement.unrealized_profit_loss",
                "show_difference": True,
            },
            {
                "display_name": "X. CHI PHÍ THUẾ TNDN",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "Chi phí thuế thu nhập doanh nghiệp",
                "field_path": "income_statement.total_corporate_income_tax",
                "show_difference": True,
            },
            {
                "display_name": "XI. LỢI NHUẬN SAU THUẾ",
                "is_group_header": True,
                "is_section": True,
            },
            {
                "display_name": "Lợi nhuận kế toán sau thuế TNDN",
                "field_path": "income_statement.net_profit_after_tax",
                "is_bold": True,
                "show_difference": True,
            },
        ]
    },
}
